### ISSUE TITLE
[iOS] 게임 선택 네트워크 디코딩 에러

### ISSUE THREAD

**Issue by Lia316** [ehdrhelr/baseball#13]
### Decoding Error
```
failure(Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], 
debugDescription: "The given data was not valid JSON.", 
underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 
"No string key for value in object around character 178." 
UserInfo={NSDebugDescription=No string key for value in object around character 178.}))))
```

- `dataCorrupted` 의 경우, 서버가 주는 JSON 데이터가 잘못된 경우가 많다고 한다
- 근데 아무리 mock api 의 데이터를 살펴봐도 잘못된 게 안 보인다 => 내 문제인가.. ㅠㅠ

**Comment by Lia316** [comment]
## 문제 원인 파악

> Hong & ZG 의 도움으로 파악했습니다 (감사합니다🙏🏻)

- https://app.quicktype.io 
에서 확인 가능

<img width="475" alt="스크린샷 2021-05-05 오후 10 06 34" src="https://user-images.githubusercontent.com/73650994/117145562-40728200-adee-11eb-8e7f-7518fbb781ca.png">

- 이미지를 보면, away의  "status" 앞에 작은 점이 계속 찍힌 것을 확인할 수 있음..!
- 계속 로그에 찍혔던 178번째 character의 string key 값 오류는 이것으로 보임

**Comment by eeeesong** [comment]
와우.. 마치 모니터 먼지같은 뭔가가 있었군요ㅠㅠ
리아 고생 많으셨습니다!!

**Comment by Lia316** [comment]
## 해결!

- 시온이 데이터 형태 수정하심

#### 추가 버그
- 데이터를 성공적으로 받았어도, 화면에 뿌려주지를 못했음
👉🏻 `dataSource.apply(snapshot)` 을 fetch 클로져 안에 넣어줌 (해결!)

<image width = "200" src = "https://user-images.githubusercontent.com/73650994/117232273-cc6ec300-ae5b-11eb-8e85-b614a7f2f9dc.png">
