### ISSUE TITLE
[iOS] 야구장 그래픽 및 애니메이션 

### ISSUE THREAD

**Issue by Lia316** [ehdrhelr/baseball#17]
## 공격 / 수비 게임 애니메이션

일단 공부할 예정~

### 돌입 전 세팅
- [x] View 및 Layer 객체 단위 나눠보기
- [x] Color Asset 등록

### 그래픽 구현 
- [x] S🟡 B🟢 O🔴 동그라미 
- [x] 야구장 필드 뷰
- [x] 야구장 base 애니메이션
- [x] 주자 이동 애니메이션

**Comment by eeeesong** [comment]
## 5월 10일 회의 결정 사항 

1. `CALayer` + `CAAnimation` 활용
2. 롤로 구현 후 리아 피드백
