### ISSUE TITLE
[iOS] 게임 선택 → 게임 진행 화면 이동

### ISSUE THREAD

**Issue by Lia316** [ehdrhelr/baseball#18]
## 작업 해야할 부분
- [x] 화면 넘기기
- [x] 정보 전달하기

## 문제 사항

- 셀 안에서는 `self.navigation` 을 호출할 수 없음

## 고민 중인 해결 방법
- 버튼 터치 시, 노티 주기 → 뷰컨에서 받아서 `self.navigation` 으로 화면 이동
  - 뷰컨에서 그런 일을 하도록 만들고 싶지 않음...ㅠㅠ
- 셀 안에서 `self.navigation` 쓸 수 있는 방법 찾기
- `storyboard reference` 를 써서 연결하기

**Comment by eeeesong** [comment]
이 부분 관련해서 계속 타이밍이 애매해서 못 말한 게 있는데,
다음의 정보를 같이 넘겨줄 방법도 같이 고려하면 좋을 것 같습니다!

1. user의 팀이 `home`인지 `away`인지
  - 현재 게임 데이터를 총괄하는 `GameManager` 객체가 `isUserHomeSide`라는 Bool 값을 가지고 있고,
  - 그 정보를 바탕으로 view에 필요한 정보를 넘겨주게 구성되어 있습니다!
2. 이 게임의 `팀 정보` & `게임 아이디`
  - 팀 정보 역시 view에 필요한 정보이기 때문에 `GameManager` 초기화에 필요하도록 작성해두었고,
  - 게임 아이디(인트로 된 그거!)는 GET 보낼 때 필요한 정보라 다음 화면들에서도 필요할 것 같습니다.
  - 다만 게임 아이디는 `GameManager`가 가지고 있을 정보는 아니고, 네트워크 객체와 관련이 되어 있을 것 같아서 필요한 endPoint를 어딘가에 저장하면 좋을지도 고민해보면 좋겠네요!!


@Lia316  시간이 이모양이니 슬랙은 그렇고.. 이렇게만 태그할게용!! :) 굿밤입니당 부디 지금 보지 마시길....

**Comment by Lia316** [comment]
앗 우선 화면 넘기기는 성공했습니다!

## 화면 넘기기
> `SelectViewController.swift`
```swift
protocol GameCellDelegate {
    func didPressButton()
}
```
```swift
cell.delegate = self
```
``` swift
func didPressButton() {
```

> `GameCell.swift`
```swift
        self.delegate.didPressButton()
````

이렇게 delegate 를 사용했습니다!

이제 여기서 정보만 전달하면 될 것 같습니다

## 정보 넘기기 

현재 다음 뷰로 넘겨드리려고 계획했던 데이터 형태는
저번 회의 때 나왔던 방향대로
```swift
struct GameInfo: Codable {
    var userID: String = ""
    var gameID: Int = 0
    var team: String = ""
}
```
였는데, 혹시 여기서 `team` 을 `var isHomeSide: Bool = true` 이런 형태로 바꾸는 게 좋을까요?
그렇다면 시온께도 다시 말씀 드려야할 것 같습니다!

**Comment by eeeesong** [comment]
아뇨아뇨! 이 데이터 자체에서 바꿀 필요는 없을 것 같고,
유저가 선택한 팀이 뭔지 아니까 앞서 받은 팀 정보와 비교하는 로직을 만들어서 넘겨주는 식이면 괜찮을 것 같습니다.

**Comment by Lia316** [comment]
아앗 저기는 그냥 팀명만 String 값으로 가지고 있습니닷..
팀 타입이 아니라서.. 

1. 값을 넘기고 로직 처리를 한다
2. 팀 타입으로 바꾼다

이 두 가지가 있을 것 같네욤..?

**Comment by eeeesong** [comment]
아 Team 타입이 처음에 파싱할 때만 쓰이는 건가요..?
근데 그럼 초기에 받은 아래의 팀 정보도 넘겨주기 힘든 거죠??
```
struct Game: Codable, Hashable {
    var id: Int = 0
    var home: Team = Team() // <-
    var away: Team = Team() // <-
}
```

지금 상황에서는 유저가 홈인지 원정인지랑 이 게임의 team 정보 자체가 다 필요한데,
만약 둘다 cell단에서 넘기기가 어렵다면 

그냥 게임 진행 화면에서 팀 정보를 한번 더 받으면 될 것 같습니다!! 
그럴 경우 지금처럼 string 값으로 된 team 이름만 넘기면 될 것 같아용

**Comment by Lia316** [comment]
일단은 데이터를 넘기는 걸 코드로 구현해놓고 위의 1번 또는 2번으로 수정하려고 합니다!

그래서 간단하게 `GameInfo` 타입을 넘기려고 하다보니까, 뷰모델에는 넘기기가 곤란해 보이더라고요
우리 MVVM 나중에 생각하기로 했으니까, 그냥 뷰컨에 넘길까용..?

**Comment by Lia316** [comment]
네네 현재 상태는 다음 뷰컨에 넘길 정보 & 서버에 넘길 정보를 간소화해서 생각하다보니까,
타입을 명확하게 하지 않고, 필요한 정보만 넘기려고 해서 저 형태가 되었습니다 😅

근데 바꾸고자 하면 바꿀 수 있기는 해요! 
아직 포스트도 구현이 안된 상태니까! 시온께 말씀 드리면 될 것 같기도 합니당

**Comment by eeeesong** [comment]
넵 그 게임 진행 화면에서 팀 이름 받아오는건 원래 그렇게 되어있던거라 전혀 무리 없을 것 같아요ㅎㅎ
그 전에 받아오니까 중복을 줄여보려고 굳이 없애보려 했던 거라 (없애 보려 한 사실은 시온에게 전달조차 되지 않았음)
리아가 더 힘쓸 필요는 전혀 없어 보입니다!!

**Comment by Lia316** [comment]
음 ㅋㅋㅋㅋ 넵! 알겠습니다! 그러면 뷰컨에다 `GameInfo` 값 넘겨두겠습니다~
