### ISSUE TITLE
Game DTO 형식 정하기

### ISSUE THREAD

**Issue by eeeesong** [ehdrhelr/baseball#19]
이슈를 파서 논의하면 더 수월할 것 같아서 하나 생성해보았습니다 :)

- 참고로 swift는 카멜케이스(goodNight)가 기본인데, json에서는 스네이크케이스(good-night)가 국룰이라고 알고 있습니다!
- 그래서 swift 변수명은 전부 카멜케이스로 되어있지만 json이나 java 사정을 고려하여 편하게 작성해주시면 될 것 같아요!! 
- 변수 이름 역시도 클라이언트에서 디코딩 시 코딩 키 설정해서 바꿔 들여올 수가 있어서, 제가 작성한 변수명이 백엔드 사정에 맞지 않는다면 마음껏 바꾸셔도 괜찮습니다

**Comment by eeeesong** [comment]
우선 swift 버전의 DTO는 작성을 해보았어요!
@Lia316 와 오후에 이야기 나눈대로 전부 옵셔널로 되어있기 때문에
데이터를 받아 온 이후, nil이 아닌 것들을 뽑아 내서 쓰면 되는 형태입니다!

즉, 어떤 데이터가 오든 다 이 DTO의 타입으로 파싱하면 됩니다

```swift
struct GameDTO: Decodable {
    
    var inning: Inning?
    
    struct Inning: Decodable {
        var counter: Int
        var isTop: Bool
    }
    
    var score: Score?
    
    struct Score: Decodable {
        var home: Int
        var away: Int
    }
    
    var batter: Player?
    var pitcher: Player?
    
    struct Player: Decodable {
        var name: String
        var info: String
    }

    var newPitch: Pitch?
    
    struct Pitch: Decodable{
        var count: Int
        var result: String
        var log: String
    }
    
    var ballChanged: BallChanged?
    
    struct BallChanged: Decodable { //1 or 0
        var strike: Int?
        var ball: Int?
        var out: Int?
    }
    
    var baseChanged: BaseChanged?

    struct BaseChanged: Decodable { //1 or 0 or -1
        var first: Int?
        var second: Int?
        var third: Int?
        var home: Int?
    }
    
}
```

**Comment by eeeesong** [comment]
## JSON

위의 DTO를 json으로 바꿔본 버전입니다!
회의 때 말씀해주신 형식 반영해서 data/error 반영 하였고,
아래에 몇가지 포인트들 적어보았습니다.

```json
{
  "data": {
    "teams" : {
      "home": "Marvel",
      "away": "Captin"
    },
    "inning": {
      "counter": 2,
      "isTop": false
    },
    "score": {
      "home": 5,
      "away": 1,
    },
    "batter": {
      "name": "shion",
      "info": "백엔드 천재"
    },
    "pitcher": {
      "name": "lia",
      "info": "iOS 천재"
    },
    "new-pitch": {
      "count": 5,
      "result": "스트라이크",
      "log": "2-2"
    },
    "ball-changed": {
      "strike": 1,
      "ball": 0,
      "out": 0
    },
    "base-changed": {
      "first": -1,
      "second": 1,
      "third": 0,
      "home": 0
    }
  }, 

  "error": null

}
```

1. 모든 값은 포함시키셔도 되고, 포함시키지 않으셔도 됩니다. 변경된 사항만 보내주시고 나머지는 null 처리하셔도 됩니다!
   - 예시)
   - teams: 1회 초에 한번만 보내고 이후엔 쭉 null
   - inning: 이닝이 바뀔 때만 보내고 나머지 경우는 null
   - new-pitch: 아직 pitch가 없는 게임 시작 시점엔 null
   - base-changed: 베이스 정보가 바뀌지 않은 턴엔 null

2. inning의 counter -> `2회` 이 부분을 뭐라고 불러야할지 몰라서 counter라고 썼는데.. 혹시 마땅한 네이밍을 아시는 분이 계시다면..ㅎㅎㅎ 구글링 해봤는데 잘 모르겠더라고요..

3. `ball-changed`와 `base-changed`
  - 제일 많이 바뀐 부분인 것 같은데요, 이 두가지는 프론트에서 애니메이션이 들어가는 부분이다보니
  - 절대적인 값 보다는 상대적인 변화값을 받는 것이 좋겠다는 생각으로 바꿔보았습니다.
  - `ball-changed`의 각 값은 추가되기만 하므로, 변화가 없을 시 0 / 있을 시 1을 보내주시면 좋을 것 같습니다.
      - 예시)
      - strike가 1 추가되어 2-2가 된 상황: **s:1 / b: 0 / out:0** (2-2가 된 상황에 대해선 전달하지 않음)
  - `base-changed`의 값은 감소하기도 하므로, 선수가 이동했을 시 -1, 그대로면 0, 추가된 경우 1을 보내주시면 될 것 같아요!
     - 예시)
     - 1루수가 2루로 이동: first: -1 / second: 1 / third: 0 / home: 0
     - home도 필요할 것 같아서 추가했습니다 :) 


------

천천히 보시고 궁금한 점 있으시면 언제든 말 걸어주세요!!

**Comment by ehdrhelr** [comment]
오오 정리 너무 잘 해주셨네요!!
정리해주신대로 데이터 전달할 수 있도록 구현해보겠습니다! ㅎㅎㅎ

**Comment by Lia316** [comment]
오 괜찮은 것 같습니다!

또 다른 의문점이 생기면 그때 다시 생각해보구!
일단은 이렇게 해도 좋을 것 같습니다!

**Comment by ehdrhelr** [comment]
호옥시 게임을 선택하고 제일 처음 보여지는 1이닝은 이 정보만 드려도 될까요??
(1이닝에서 pitch가 진행됨에 따라 new-pitch, ball-changed, base-changed가 추가된 json 데이터 전달드릴 예정)
더 필요한 부분이 있다면 추가하겠습니다..!!

```
{
    "data": {
        "teams": {
            "away": "Marvel",
            "home": "Captain"
        },
        "inning": {
            "counter": 0,
            "top": false
        },
        "score": {
            "away": 0,
            "home": 0
        },
        "batter": {
            "name": "시온",
            "info": "백엔드 천재"
        },
        "pitcher": {
            "name": "리아",
            "info": "iOS 천재"
        }
    },
    "error": null
}
```

**Comment by eeeesong** [comment]
@ehdrhelr  넵넵!! 너무 괜찮습니다 :)

**Comment by eeeesong** [comment]
### (일단최종) JSON 

리아가 말씀해주신 부분 반영한 (일단최종) JSON 입니다!!

@ehdrhelr  바뀐 부분은 base-changed 부분 하나예요!

```json
{
  "data": {
    "teams" : {
      "home": "Marvel",
      "away": "Captin"
    },
    "inning": {
      "counter": 2,
      "isTop": false
    },
    "score": {
      "home": 5,
      "away": 1,
    },
    "batter": {
      "name": "shion",
      "info": "백엔드 천재"
    },
    "pitcher": {
      "name": "lia",
      "info": "iOS 천재"
    },
    "new-pitch": {
      "count": 5,
      "result": "스트라이크",
      "log": "2-2"
    },
    "ball-changed": {
      "strike": 1,
      "ball": 0,
      "out": 0
    },
    "base-changed": {
        "first": {
            "in": false,
           "out": true
        },
        "second": {
           "in": true,
           "out": true
       },
        "third": {
           "in": true,
           "out": true
       }
    }
  }, 

  "error": null

}

```

**Comment by ehdrhelr** [comment]
@eeeesong 감사합니다!!
 inning counter는 실수입니다 ㅠㅡㅠ ,, 1 == 1회로 바꿀게요!!

**Comment by eeeesong** [comment]
아직 네트워크 받아온 뒤 GameDTO 형식을 프론트 내부 타입에 적용하는 부분을 구현하지 못해서 
이 이슈는 조금 더 열어놓겠습니다!
