### ISSUE TITLE
[iOS] 게임 진행 화면 서버 통신 구현

### ISSUE THREAD

**Issue by eeeesong** [ehdrhelr/baseball#3]
- [ ] `수비 턴` PITCH 버튼 누를 시 GET 요청 (all 로직 @서버)
- [ ] `공격 턴` PITCH 후 게임 상황 변화 시 GET
- [ ] 각 화면 업데이트
   - 5/4 회의: pitch 후 변경된 정보 일괄 전송
   - 5/7 회의: 변경 단위에 따라 전송
- [ ] 턴 결과 사용자에게 노티
- [ ] inning 정보 변경 시 공격/수비 side 전환

**Comment by eeeesong** [comment]
## pitch 후 공격 턴 사용자의 화면 업데이트?

- 다른 게임을 생각해보면 턴 당 제한시간이 있을 것 -> pitch를 눌러야하는 제한시간
- 제한시간이 3초라고 한다면...
   1. 3초 내 어느 순간에 pitch
   2. 공격 턴은 3초 후 GET 요청 -> 요청을 반영하기 전 또 pitch가 발생하면 꼬일 수 있을 듯 + 애니메이션도 보여주려면...
   3. 수비 턴 pitch 누르기 전 3초 정도 freeze -> 그동안 공격 턴 사용자는 pitch 결과를 확인, 확인 버튼 터치 등 서버에 확인 노티를 보냄
   4. 수비 턴은 3초 후 다시 턴을 시작해도 되는지 서버에 확인, 가능하다고 보내면 다시 1번으로 돌아감

**Comment by Lia316** [comment]
## 의견
- 버튼 비활성화 과정이 필요할 것 같습니다!
- (공감) 확실한 안정성을 위해서 서버 확인 과정은 필요할 것 같네요 🥲

**Comment by eeeesong** [comment]
내일 핵심(?)만 빠르게 적용하면 좋을 것 같아서 마이너한 변경 사항들은 미리 반영을 해뒀습니다!
시간이 늦었으니 따로 태그는 안하고 내일 아침에 말씀 드리겠습니다

1. endpoint 업데이트 -> 서버 주소 반영 + port 속성 추가 (8080)
2. DataDTO 추가 -> 뭔가..네이밍이 구리긴 한데 마땅히 떠오르는 이름이 없어서...
   - 모든 데이터가 data / error 에 감싸여서 오므로, 아래와 같은 데이터 형식을 하나 추가했습니다.
   - 그리고 viewModel에서 request 시 각각 `DataDTO<[Game]>.self`, `DataDTO<GameDTO>.self`를 타입으로 넘겨주도록 수정했습니다.
```swift
struct DataDTO<T: Decodable>: Decodable {
    var data: T?
    var error: String?
}
``` 
3. DTO를 최종 형태에 맞게 변형했습니다
   - `teams`, `inning`, `pitch` 에 각각 사소하게 부합하지 않는 부분이 있어서 수정했습니다. (코딩 키, 데이터 형식 등)

--------

내일은 pitch 버튼 누르면 pitch 보내는 부분, 그 결과에 따라 화면에 뿌려주는 부분부터 작성을 하면 될 것 같습니다!

**Comment by eeeesong** [comment]
상황 상 적용 못할 사항들이 많을 것 같아서 우선 이 이슈는 닫아두겠습니다!
